version: '3.8'

services:
  franchise-api:
    build: .
    ports:
      - "${SPRING_SERVER_PORT}:${SPRING_SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_SERVER_PORT: ${SPRING_SERVER_PORT}
